package org.example;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public class Day4 {
    public static String PUZZLE;

    public Day4(String puzzle) {
        String words = """
                XMXMXSXMMSSSSSXMMAMXAAXXMXSXMMSMXMXXMMMMMXXMXXAMSMSSSMXMXSAMXAMAMXSMSMXMXMAMAMAXAMSSSXSXMXMAXAMXSMMSSMXSXXSSXSXSSSMMSSMSXAMXXMAMXSSXSMXMSMMM
                MMAMAMASXAAAXAAMASXMXMAXSAMAXAAAAXMASAAASMSMMMASMXAAXMMAASXSXMXASMAAXMAXSMMXSMMAXSAMXASMMSMSSXXAMXAAMXSAMXMAASAMAAXAAAAAXSASXSMSSMSASMSASAAX
                ASASMSAMMMSMXXXMAMAMSMSMSASMMSSSMSAASMSMSAAAASXMXMMSMMAMASAMAMSASAMMMMXMSAAAAAXAXMAXMXMASMAAAMXSMMMMMMXAMAMMMMAMSMMMSMMMMXXMAAAXAAMXMASASMMM
                XSAAXMAMSAMXASXMMSAMXAAASMMAAMAAAAMXMAXXMXMSMSAMXSMAMXAXAMAMAMMAMXXAMXMASAMXSAMASMMMAAMMMMAMSMAMAXAMSMSMSSSMASXMAAXAXAMXASXMSMMSMMMMMAMAMASX
                MMXMASAXMASMAMXAXSMSMSMXMAXMXMXMMMMXAMMSXAMAMSMMAXMASXMSXSAMMSMXMXMMXAMAMXXAXXAAXASXSSXXXXSXAMASAMXSAAAAAMAXAMXSSMMMSMMMXMAMXXMSAAAAMAMAMSMM
                XSAMXMAMSAMMAMSMMMSMMXMSSXMMXSAXMXMSMMAMSMSAXMAMXXSAMAASAMXSMAMSMSASMXMSSMMSSXMXMXMAAAASMMMSMMAMXXMMMSMSMSSMMXMXMXAXAAAXASXMMAXMSMSSSMSSSMAA
                AXAXSXMASXXMAMAAAXAXMXMAMAXAAMAMSAXAAMSXSXSXSAAMMMMMSSMSAMXXXASAAMAMXMSXAMXMAXSMSMMMMMMMAAAAMMSSSSMXXMXXXAAAMSXMASXSMSMSMMAASXMXAMXXAMAMAMMM
                MMSMMASAMMMSASMSMSMSSMMMSSMMSSMMSMXMSMXAMAXAMMMMXMXAMAAXMASMSMSXSMSMMMMSMASMAMMAXXAAAAASXMMMSXMAXAASMSMXMXXMMAXAXMMMAAXMASMMMMSSMSSSSMSSSMSM
                XAAASAMAMAXSXSXMAAAXAMMXMMAXAAAXXXSXAMXAMMMXXAXXXMSASMMMMAXAAAMAXAXAXAAAXXMMSSMSAMXMMMMSSXMASMMMMMMSAAAAXMMSXMSMMAAMSMXSAMXXXXAAAAMAXAAAXAAX
                MXSMMXSAXSASXXMMMMMXAMXAXMSMSSMMXXAXMSSMAXSASXXSAAMAMMXSMSMSMSMAMXMMSMSSSMSAXXAMMMSAMSMMMSMASAAXXMAMXMXXSAAXAXAASMMMXAAMAMMMSSSMMMSMMSMSMSMS
                SAMAMMMMSXAXMMMSXASMMMSXSAMAMMAMMMMMMAXXMMMASXAMMAMSMMAAAMMXMMMMSSMMSMAMAAMMXMXMAAMAMAAAXMMMSMMXSMXSXSAASMMSMMXXMASXMMMSMMSMXAASMAAAMMAMAMXX
                XASAMAAMSMSMAXAAMXMAAAAAMXMAMXAMAAXAXSSSMSMAMMXMMXMXAASMMMXASXMASAMASMAMMMMSMMSMMSSMMSSMMSAXSXSAXAMXAMMXMAMAMSMSXMAAMAAMXAAMMSMMMXSMMMSMMMAM
                SAMXSSSMSAAMSMSSSSSSMMSMMMSSXSMSSSSSSMAAASAMXAMXMAMMSMXAASMMSAMXMAMAXMAXASMSAAAXMAAMAAAXASMSMAMMSMMMMMXAMXMASAAMAXMSSMSSMSSSMMAXSMXASXMAXMAM
                MAAXXAXAMSMXMAXXAAMXXAMXAAXXMXMAMXAMAMSMMMXSMSSMSAXAMASXMMAASMMXSSMMMMXSMSASMMMAMSMMXXAMXXXAMSMAAAAXAMSMSMSMMMMMXMXXAAAXXMAXASAMMASAMMSMMSMS
                SSMSMSMSMASAXXXMXMXXXSMSMSXMASMSMSMMAXXSXMASAMAAAMMSSMMAXSMMMXMMSAAMSSMAAMAMXSXSXXMMSMAXASXMSAMSSSMXSMAXAAAASXSMSAXSMMMSMMAMMSMMMAMAMXAMMAAA
                AXAAAAAXMAMMMSMAMMMXMMASAMMSAAAAASASXSASXXAMXMMMMXAAAASXMAXMMAMXSMMMAASMMMAMMSAAAMSAMSAMMSAMMAXAXXXAXSSXMSMSASAAMSMSAMASXMASXMAXMMSSSSMMMXSX
                MMSMSMSMMSXSAMAMAAMXSMAMAMAMSSXMASAMAMMXMMXSAXXSSMSXSMMAAXSMSASMMSMMSXMXXSXSAMSMXMMAXXMSXSAMSSMSMSMMMAMXMXMAMMMXMAMSAMASASAMASAMAAXMAAMSSMMX
                XMAAMMMXAMAMASMXSMSAMMMSSMXXMMXXXSAMXMMAASASMMSAMXXAMXMASXMAMASAAAXAMMSMMXMAXXAXAMSMMAXMXSAMXMAAAAAXMXMMMAMXXAAMSMXSAMASXMAMXMXAMMMMSMMAAAAS
                SSMSMAXMASAMAMMMMAMXSAMXAXSAMXXMASAMXMSASMASASMMMAMAMXXMMMMAMMMMSMSMMAAMXSAMXSMMMMAASXMSMSMMAMMMSMSXAASXSMMMSXSXAXMSXMAXMSSMSMXMAASAXXMMSSMA
                XAMAMXXMXSAMMMSAMMMASMSMMASAMXXMAXMXAASMMMSMXMASMAMAMSXSAMXXMMAXXXXAMSMSAXAMXMXASASXXXMAXXASXSMMAXXXXXSAAASXMMMXMSMMMMMMMAMXAXAXSXMASMXXXAXM
                MSMMMSXSAMXSAAXXSAMMXAAAXMXXMXMMMXSMMMXAXXAMMSXMSXXAMAAMMMSAMSXSSMXAMXXMAMSMMASXSAMXMSSMSMMXAAXSAMXMXSMMMMSXSAMASAXSAMXXMASXSMXMMAMXMAMMMAMX
                AAAAAMMMXMAMMSMMSAMXSSSSSXSXSXSXXAAXXAXMMSMSAXXMAXMAMMSMMAAMXMAXAAXMXMMMAMXAMAXAMMMXAXMAMAXMMMMAMSMMMSAMXAMMMASXSAXXAXXMAMSAMAMASMMAMAMXAXMS
                SSSMSSSMMMAMAMXMXAMXAAAAXAAASMSAMSXMXMMMMAXMXSMMAXSAMAXXMMMSAAAMMSXMAMAMSXSAMMSXXAAASXMAMSMXAAAMAAAAAMMMMASXSMMXMXMSSMSXSAMAASAMXMMSMMSMXMAA
                MMMMXMAAXSXMASXMSSMXMXMMMMMASAMSMAASASASMSSMAMXMAMAAMXMASMASMSMXXMAMMSAXXASXMMAXSMSMXAMAMXXSMXSXSSSMXSAASAXAASXMXAMXXAXAAASXMMAXSMAXAMAASMXM
                SXXSASMSMMASMSXXAMXAXSMSXSAXMAMMMSSMASXSAAMMAMAMMSMMMXMSAMXMAAXXSSSMAMMSMMMMSMMXAAXXAMSMXMAMAAMMMAXMAMMMSSMSMMMMSXMASXMMMAMMASMMAMAXASASAMXX
                XAXSASXXASXMAXXSMSSXSAMXAXAMXXMSAMAMMMAMMMMSASXSMAMXXAMMXMAMMMMXMAXMXSMAAXXAAAXXMXMAMXAXAMXMSMSAMMMMAMSXMMMAAAXAAMMMMAXXXXXMAMAXMMMSMMMXMSSM
                MSMMAMMXXMXMMMAXAAAXMMSMSMSMXSMMMSMMAMSMXMMSXSAXMAXMSSSMAMASXASMMSMXSAMSMSASXSMMXAAAMSASXMAMXASMMXMMAMMAMSSSMSMMXSAAMSMMMSMMSSSMXAXAMAMMXAXS
                SMAMSMSSMMXAXMMMMMSSMXSXMAXXXXAAMAMSMMAMXMAMMMMMSXSXAAMMAXAXMXMXAXAMXAMXSAAXAAXASASMXXMAMSMSMXMXMAMSSMSXMAXMXMASASMSXXASAAAMAMXMSMSMSASAMSSM
                MMAMXAMXAXSMXAASXMAAMXMAMSMSXMXMMAMAXSASMMAMAAAAXSAMMMMSMSMSSSMMMMAMSXMMAMXMMMSMMXAXXXSAMXMMAASAMAXAAAXMASMSMSAMASAXMSAMSXXMAXAMAMAXSAMXMXAM
                SSMXMMMMSMMXSMMSAMSSMAMAMAMSASASMXSAXSAMXMMSMSSSSXMXSAAAAAAAAAMAAXAMAAXMMXSXAAXASMMSSMMMSSMMSXSXXSAMMAMXMAXMASAMXMAMAMMMMMSSSSMSASAMMASXMSAM
                MASXSMSAMASASAXSAMXMMSMMSAMSAMMSAAMMMMSMXXAAXMAMXMMASASMSMMMSMSXSSMSSMMXXAMXMXSAXAXAXAAAMXAAMMMMMMAXXASMMMSAMSAMXMXMXMSAXAAAAAASAMXMXAAAAXAS
                SXMXAAMASMMASMMSXMXMAXAASMXMAMMMMMMMAMASXMMSXMAMXAMASXMMMAMAMXSAMMMAAMSMMAMXSAMASAMASMMMSSMMSAAAASMMMXMAAAMXMSMMXAAXAMMMSMMXMMAMAMAXMMSXMSSM
                MASMMMMXMXMAMXMSXSAMASMMMXAXAXAAXXASXSAMMXMXMXAMXSMASASAMASMXAMXMAMXMMAMXSMSMASAAASAMXXXAAXAMMSSXSMSMMSSMXSAMXSXSXMXXMAXMASXXMAXASMMXMMMMSAA
                SAMASMMMXAMMMMAMASMMXSAMXSMSASMSSSMSMMMSMXMAXSASMMMMXAMMSAMXMMXASXSMMSMXAAMAMAMMSMMMSMSMSSMSSMXMAXAAMXAXMAXXSAMMSAMASMSMSAMMXSMSMAXMASXAXMXX
                MASXMAASMMMSAMAMMMASXSXMXMXAMXMAMAXMASAAXSMAXSASXSASMMMMMAMSASAMXAAXAAAMSSSSSXSXAMAXAASXMXMAAASASMSMSMSSSSMAMXSASXMXXAAXMMMMAAXMXAMSXMMSSMMM
                SAMXXSMXXMASXSXMASAMXMAMSMSSMASASMAXSASXSSSSMMMMASASXSMXSMMMAMXSMSMMSMSXAAAAXMAMXSMSMSMMMAMSSMSXMAMAAMAAAXMAMXMMSAMSMMMMMSAMSSMSMSMSAXXXAMAA
                MAXSAMMSSXAMAMAMXMASXSSMSAAXSXSMSXMSMAXMMXMMASMMMMXMAXXAXXXMSMAMAXAXMMXMMMMMMMSMMMMXMXAASAMMMMMAMMMXMXMMMMMAXAXAXAMXAAXAXMAMXAXXAXXSMMXSAMSS
                SAAMAMAAMMSSMSAMASAMXAAXMMMXAMXMMXXAMSMMSXMSAMXMXXAMAMMMMMSAMMAMXSAMXAXAMASAXXAAAMAMAXSMSMXMAAMAMMAMMSMMAMSMXMMMSMMSSMSSSSSMMMAMAMXMSAASAMXX
                MMSXAMMXSAXAASASASASMSMMMAMXAAXMAMXMXXAAAMMMMSAMMMSMXXAAAXMASMMMXAMMMMSSMASMMSSSMSMSAAMXSASXSSSSSMMSAAASXXAMXXSMSAAMAAXMAAXAXXMAASXAMXMMMSSX
                XAMMMMXMMXSMMMAMAXAMMAAXSAXSAMMMXMAMXMMMSMMAXSASMAXMASMSMXSAMAAXSAMXXAAMMMMAAXMMAAMMXSXAMMMAAAAXXAAMMSMMMMASAAXASXMSMMMMSMSMMXXSXAMMMSSMAMXS
                MXSASAAXAAXXAMAMXMSMSSSMSAMSMSAAAXSXSXMXMAMSMSMMMSXSAXAAAAMASMMMSAMXMMSSSMMMXSAMSMSMMMMMMMMMMMMMMMMSXMASAMAMMSMAMMAMAAXAAXMASMMMMSMSAAMMXSAX
                MASAMMMMMSSXSSXSAMXAMXAAMXMSASMSMMAAXAMXMSMXAXXMAXMXAMSMAMSXMAMMSAMXMXXAAXAXASXMAAAAAXAXXXAXMXSAMAAAMSAMXMXSAMMAMMASXMXSXXSAMAAAXAAMMMSMSMMS
                XMMXMXXASMXAMAASXMMMMSMMMAAMAMXXXXMMMMMMXXAMAMAMXSXXMMXXMXSASXSASAMAAXMSMSSSMMSMXMSSMMMSASMSMMSASXMXAMXXXMXMASXMXSXSAMAAAAMMMSMMSMMMSAXMAAAX
                SAMXMSMMSAMSMSXMAMXSAXXASMSMSMMMSXXSAMXXAMAMMMSMASAMXAXAAAXAMAMASAMXMXMXAAXMAASMSAMXMSSMMMAXMASXMAXSSMSXSASMAXAXMMXSAMSMAMXSAXAMAXAAMASXSMMS
                MASMMMXSMMMXAMSSXMAMAMMXXAXXXXAAXMASASMMXSAMAAAXASASMMMSMXSAMXMMMXMAXSXMMMSMMMSAXAMAMXAAXMAMMASMXMXAXAXXMAAMAXMMAMASAAXAMXXMASASASMMMMMXXAAX
                SAMAAAXMAMAMAMAMAMMSAMMSMMMSMSMSXSMMAMXAMSMSMSMMXSAMAAXXAASAMXSMMMSXMMMAXXXXSAMXMXSASMMMMSMXAMXXAMMMMMMMMMMMSSMASMXSMMSMAXXMAMXMAMMASASMXMMS
                MAMSMSMSAMSSSMMMAMMMMMAAAMAAAAAAASXMAMMSXSASXMAXXSASXMAMMMXXMAXAAMAMAAAMMMAMMAXXMXSXSAAMASXMSAMMXXAAAXMMAXAAXXMAXAMXMAMXMSMMMSMMMSSMSAXASMAX
                MSMAAMAMXSAAXXSSSSXAAMXMMMSSSMSMSMASASAMAMAMASXMXMAMMAMXMMMMMMSSMSXAXAMSASAMSXMASAMXSMMMMMAXMASAASMXSAMXSXMMSMMSXSAAMAMAXAXAXAMSAAAXMMMMAMXS
                AAAMMMXMMMMMMAMXXMMMSMMASAMAAAXXAMMMXAMMMMAMXMAMMMSMMXXAASMXSAAAAAMSAMASMXAMAASAMASXXXXXMXMMSAMMMSAAAXXXMXSAAXAMXASMMSMSSXXSMSSMMSSMMXSAAXAA
                SMSMMXAMAMXAAMMSMMASAXAAMAMSMMMSXSXSMMXMXSXSASXMMAMAMSSXSXAAAMSMMSAMSSXMMSSMSXMASAMMSMMMSAMAMXMXAMMMMMMAMAMAMMSSMMMMAXAMMXAMXMAXAAMMAAMXSMMX
                XMMAXXSSMSSMSAAMAXMSASMXXXMAAAXSASMSXMAMMMASASAMMAXMMAXXMMMMMXXAMXMXAXAAAXMAXMMMMAMXAAAASAXSXSMMMSXXAMXAMAMXSMAAXXMXAMAMAAMSMSAMXSAMMXMAMAAS
                MASAMAAAMXMAMAMSSMXMAMXSXSMSXMSMAMXMASASAMAMXMASXSXSMMMSMSASXMASXASMSSSMMSMMMSAXSAMSSSMXSSMXMMMAXMAXSMSXSASAAMSMMAXMSSSMXMMAAMXMXMXXSAMXSAMA
                MXMAMXXXMAMMMAMAXMXMXMASAXAAMMXMAMASMMASMMAMSSMMAXMMAMSAAXSMAAAXMASAXAMMAAAAASMMSAXXXXXXMASMASXSMMSMMASASAMMMMXMMSAAMAXMASMMSMSMXMSMSASASAMM
                XAXXMMSMMSSXMXSXMMMSAMXMAMSMSXAXXSASAMXMMSMSAAAMAMASAMMMMMMSXMASAAMMMAMMSSSMMSXXSMMSAMXMMXMSXMAAXXMAMAMAMXSMXAMXAAMMMXMMXSXAAAAMAXXASAMXSASX
                SMXSXAAAXAAMSMMXSAMSASMMSMAAAMAMXMASXMMAMAMMXMMMMMAMAXXASXMASXAMXMMXMAMXAAAXAMXAXAXAAMSXXAAMMXSMMSMMMMMXSASMMSSMSSSSXMASMMMSMMMXXSMXMSMASAMM
                AMASMSSSMMSMAAMAMAXSAMXAAXMSMASAXSASXMAXSXSASXMASMXSAMSMMMSASMMSAMXAMXXMXSMMXSMMSMMMXMAASMSMSMXAXXXXAASMMXSAAXAXAMAMAXXMAXAXMASXXMASMMSMMXMX
                XMASAAMXAXAMXMMMMMMSXSMXSSMAXSXXMMASASAXSXMXSASAXAAMAXAAAAMAXXAMAXSASAMMMMAMMMXXAMAMXMMXMAAMAASAMXXSSMSASMMMSXMMXMAMXSAMSMSMSASAMXXAAAMXMASX
                XMAMMMSMSMSSMSAXASXMAXAAXAXSSMMSSMAMAMMXSAMAMMMSSMMXMMMMSSMSMXMMAMXMAXAAAMAMAAMMMSAXMXSAMXMSMMMXSXMAMAXXMAMMMAXAXXXAAMAMAAMAMASAMMASMMXAMSMS
                XMAMSASAAXXAAAASXXAMXMMMMAMXAASAAMXMMMSASAMMSAAXMASXSXXAXXAAXMXSAMXMSMSMXSAMMSSSXSASMMSASXMMXMSAMMAMMSSSSSMASMMMSSMMXSAMXSMAMAXMSSMXAMSMSAAA
                MSASMASMMMSMMMXAMSMMAAAMMXMSSMMMXMMSAAMASXMASMSXSAMXAAMSMMSMMSASASMMAAAXMAMMSAMXAMAXXASXMAAAMXMAMSSXMXAAAMMMMSXAAXAAAXASXMMMMMSAXAXSXMAMMMMX
                AMMSMAMXMAXAAXXAAAAMASAMSAMXXMXSSMAAMXMASXSMXAXASMMMMMMMAXAAXMAXAMXMASXMSAMXXMSMXMMMMXMMXSMMSXMXMAMAAMMMMMAXSSMMSSMMXSAMXSAAAXMASMMAMSXSXSXM
                XASXMASMMXXSMXMAMSMSMMAMMAMAMSAXMASXMXMXSXAXMXMASXXXXAAXMMMMSMSMXMASMXXAXXXAMXXAMXAAXMXAAXAMXMSMSASMMSMAXSMSSXXAAXAAAMAMAMXXSXXMAXXMMSASAMMS
                SXMXSASXMSAXSXSAAXAAXMAMXMMASMMSSXMASMSMSMMXXMMAMXMXSMXMAAXXSAMMXXMSAMXSMMMSXSSSSSXXSASMXSAMAXXASASAAMMMMSXMXAMMMSMSMSAMXSSXMASXMXSXMMMMAMAX
                SAMMMMSAMXAMAMSAMMSMSSMMSXMXSXAAAASAMASAMXXXSXMASASXXAASXMSAMAMMSMXMMMAAAXXMAXXMAXXXAMSAAXASMSMXMAMMMMAMAMAMMXSAMAAAXMASMAASAASASAMXMAMSMMSS
                MAMXAXSXMMMMAMXXXAXXMMAAAASAMXMMSMMSMAMXMMMMMASASASMMSMXAAXAMMMAAXMMMMSSMMSMMMASASMMMXMAMSMMAXAMMMMSMMMXAXAMXASASMMMSXSMMSMMMXMAMAMAMAMAXMAS
                SSMSXMMMSASXMXMMMMSASXMMSAMAMASXAAXMMASAMAAASXMMSMMAMMASMMXMMAMMSMMAXMXMXAAMXMAMAMAAXSAMXAAASMSMSAAAAASMXSASMASAMXMXSXMAAXXMASMAMMSSSXSSSMAS
                AMASMAAMXASMSAMSAMMAMMXMMMSMSASMMSSXSASASMSMMAMXXAXSMMMMMASASASMAMSAMSAMMSXXMMMXXXSMMMAMSXSMMAXAXMAXMXSAASXMAMMAMXXASXSAMXMAAXXAMMAXMMMMAXAS
                XMAMXMMSMAMAXAMSASMMMMASMMAAMASAMAMMMMMXMAXMMMMMMSMMMASAMXAASMXMAXMAMMAMAMMSSSSXMAXXMASMAMMAMMMMMXMASMSMMMMXSASAMXMASASXAAMMASMMSMMMSAMXAMXS
                AMASXSASMAMMMSMMAMMSMSAMAMMSMMMMMAXSASMSSXMSAMXSAMASXMMXSSMMMMXSMSAMXSSMASAAAAMAMSMMMMMMAXXAMSSMMMSAAAMAXXXAAXSXMXAMMAMXSAMSASAMMASASASMSSMM
                ASMMXMAMXAMXAAASAMXAAMASXMXAXMAXMAMMASAASAAXXSAMXMXMAMMSXMASAXXSAXXXXMASASMMMMMXMAAAAAXSAXSAMASAAASXMMSSMMMXXXSASMSMMSXMASXMASXMSAMAMAMAMMXM
                MXXSXMAMMSSMSSXMXXXMMMXSXAXMXMASMMSMAMMMMMMSSMMSSSMMSAXMASAMXSAMAMAMMXMMXXAXSXSAMXMXXMXMXXAAMASMMMSASAMXAASASXXAMAXXAAXSAXXMMMMAMMSSMAMSMMAS
                XAAXAMAXMXAXMMXMMXAXSAAMXMMXMSXSAASMAMXAXXAXAAAAAAAAMXXXAMXSAMMMXMXMMAXXXMMMMXMAXSXSSXSXSSMSMXMXMASAMXSMXMXAAMMSMMMMXSXMMSXXMAXXMXAMSSSMASAX
                MMSXXMASMSSMMMAAMXXMAMXSAMAXAMAMXMXSMSMXSMASXMMSSSMMXMSMXSXMXSXMXXXASXSXXSAAXSXMMXAMAASAMAXXMASXSMMXMASMMSMMMXAMASAXXMAAMMAAMAMSMMXMAMAMAMAS
                XAAXMMXAMAXMAMXAMXMAMXAXASASXMAMASXSMMMAAMMMXXMAXMASAAXXAMXSAAAASXSMMAMMMSASMXASAMXMMMMAMAMAMXSMAXMSMAXSAXAAXMASASMSASMMAMSMMXMAASXMMSAMXSXA
                MXSAXSSMMSSSMSSSXSMASAMXAMASMMAXASMXAAMMSMAAXXMASXASMSMMMSAMMSMMAMMAMAMAMMXMASXMSAAMASMMMSSXMMMMSMXAMAMMMXAMXXAMASASMMSMMAAAXMSSMMAAXMMSASXM
                SAXAMXAMAMXXSAMXAXMASAMMMXAMMSSMXMAXMMSAAXMSSMSMMMASMXMAMMAMAXAAMAXMSXSAXXAAMXMAMSMSAMASAAAAXXAAXXSXSXMASXSSSXAMAMXMAXXSMXMASMAMMXXMSXAMASMX
                MASMMSXMAXMXMMXMMMMMSMSASMSSXAXASMSXMMMXSSMAAASASMSXMASMMMAMSSMMXSMXAXMMXSMSMASAMAMMXXAMMSSSMMMSXXMASXMMSAMAMMSMMMASMMMXMAXXXMASXSMASXSMMMXX
                MXMAXSXSXMXAXSASAXAXMASASAMXMXSAMAMMSXMMXAAMXMSAXMAAMAXMAMSSMAMMXMAMMSMSASAAMMMASAMAAMMMMAAMXMAMMXSASXMMMAMSMAXAXXAXMAMASMMSSMXSAAASXAXMAMXX
                SMSSMMAMMSSMMSAXASMMMAMMMMMAXAAXMAMAAAAMXMMXMMMMMSSSMSSMAMXAMAMXAMXAXAAMAMXMXMSAMXMMMSAAAMMXMMASMASMSAXAMMMMMSSSMMMSSMSASAAMASMMMSMMMXMMAMXM
                AAAMSMAMAAAMAMMMXMXAMXSMMXSSMMAMMASXSXMSSSMXSXAXAMAXMMAMMXSAMSSMMSAMMMSMSMMSAAMAMXXAASXSMXXAMMAXMASASXMSSMAASAMXAAAAXAMXSMMSMMXAAMASAXSMASAA
                MSMAASXMMSSMASAMXASXMAMMSAAXMXAAXAXXMAXAAAAASXMSMMMMMSAMXAMMMMAXAAAXAAAAXAAAMMMMSXMAXXAXMMMXXMMSXAMAMXXAAXSMSAMSXMMMSMSAMXAAMAMMXXSMSAXSAXXS
                XMXSXSXAXAXXAXMXMAMSAMXAMMSMSSMSMXMASMMMSMMMSAMAXAXSASAMMSMSAMSMSSMMSSMSMMMSXXAAMMMSMMMMSSMXSASAMXSSMSMSAMXXXAMMASXMAXMXSMMXMXMAXXAAMMMMMSMM
                XMXMAXXAMXSSSXSAMSAMXXMASMAXAAAXASXMMAMXAAAAMAMXSASMAXMXXMASXXXAMMAXAAXAXXXAXSMMAASASAMXAAAAXMMAAMXXAXAMAASMMSMMAMASXSMXSMMSMMXAMSMMMXSAMAAA
                MSSMMMXXAXMAMAXAMXAMMSMMMXMSSMMMXMASMMMSXSMSMSMMXMXMXMMAMMMMXXMAMSAMMXSXMMXMMXMXXMSASXMMSSMSSXAMMSMMXMXMMXMAMMAMSSXMAAXAMXAAASMSMASXMASASMSS
                SASAXAMXSMMAMSSSMSXMAAAMMAXXXMAXXMAMAXAAAMXMAMAMASASMSMAAASMMMSAMXXXAAXAMXAXXAMXSXMXSASAMXAMXMXSAXAXXMAMAXMXMSAMAXMMSMMXSMXSXMAASXMXMAXMMAAX
                MAMMXSAMAAXMXXAXAXSMMMSASMSSSMSMAMXSXMMSXSAMXSAMMSASAASXXXMAAAMMMMXMMMSAMAMSMAXSAXSASXMASMSMXSAMAXSAXSAMSSMMXSMMMSAAMMMMXMAXMMSMMXSXMSSSMMMS
                MAMMAMMSSSMSXMMMMMASXAMASAAAAAASAMMMMXMXMXAMXMXMASMMMMXMSMSMMSSXSMMSAAXMMAAXXAMXMXMAMMSASAMAMMASAMAAMMMXMAASAXXAMXMXSAAAXMASAXXAMXSSMMAXXAMA
                MASMASAMAXAMXXAAXSAMMSMAMXMXMMMSXXAAMXMAMXAMXMSMXSMSXMAAAMAAXMAMAAAMXSMSSSSSMSASXMMSMAMAXMMSMSAMXSMXMAXAMSMMMSSMSAMXSXMMXMASMMXAMAMAMMAMSXSS
                SAXAAMAMMMSMMSXXXMAMSAMXMMSMXSAMAXSXSASASMSAMXAMXSXSASMSMSSSMMMAMMMSMMAAAAAAAAAAASAXMSMMMSAXMMMAAMXSSMMMXAXMAMAMXAMXMMXMAMASMMSSMMXAMMSMSAAX
                MMSMASXMXAAAXAMSSSXMSXSAMAXAXMAMMMXASASASXMAMMAXXMMSAMXMXMXMAAXSXSAXAMMMSMMMMMSMXMASAMAMAMASXAMMMSAMASASXMMSMXAASAMAMASMAAAXAMAMXMXASXXAMMMM
                XXAXMAXXMSSMMMSAASAMXMSMMAMXXSSMSSMAMAMXMXSAMXSMAMAMXMAMXMASMMSAMXMSSSXMMMMXXAXMAMXMMSAMASMAXXSMAMXMMMMMAMASXSMMSAMMMAMSAMXSSMASAXMMMXMAMSAA
                MSMXSAMMAMAASXMASMXXAXXMMSSMAXXAXAMXMXMASMMAXAASAMSSMMAXMSAMAXAXAAAMXMAXXAMXMMSMSMAXXSASXSMMSMMMSMMSXMASMMAXXMAASXSXMAXAXMXAXSAMAXSAXASAMMMS
                AMAAMASMASMMMMXMAXXSSSSXAAAXSSMSMSMSMASASXSAMXXMSAMXASASASAMXMSXMMSSSSSMSXMXXMAAAMSMMMXMASXSAAMAMAAAMSAMXMAMMXMMSAXXMXSMMSMSAMXXAASMMMSXXSAM
                SMMMSAXMMSMSMAAXMAXAAAMMMSSMMAMAAAAASXMMXAXAXSAMMXXSXMAAASAMAAAMSMAAAAAASMSXASMMMXXAAXMAMXSMSSMASMMMXMAXXMAXSASMMAMSMXMXAXSMMMSSMMSXMASAMMAM
                MASAMMSSMSMAXSMMMXMMMMMAAXAMSSMMSMSMMXMASXSAMSAMXAMXXMAMMMXSSSMSAMMSMSMMMAXMAXMASASXMMSMSSSMAXMAXXXXXSXASMMAAAMXMXAXAAMMSMMXAAMAMXSMMMMAMMSM
                SAMXSAAMASXMXMMASASXAAXXSSXMAAAAXAAMSMMASXAXMMMMMSMMMAMXAAAMXMXSASMXXMXXMMMSXMXAMAMAMAASXAXMAXMAMSSMXXMAXAXMMXSXMMMMSMSAXAMSSMMMMAXMMXSAMXAS
                MXSASXXMAMAXMASASASMSMMSAMXMSSMMMXMMAAMASMMSSXMAAAAXSSSSMSMSXMASAMXSASAMSMASASMXSSSMMSSSMMMASMMAMAAXSASXSMMXXAMAXAAAMAXASMMMAMSXMSSXAXSAXMAS
                MSMASXMMSSSMSXMXSAMMXAXMAMXMAXASMSSSMSMAMAMAMASMSSXMAAAXAAXMAMASAXAXMMXMAMXSAMAAAXMXXXMMAMXSAASXMSMMMAMAAMSMMXSSMSXSSMMMMXAXAMAASAMXMMXSMMSX
                MAMMMMMAAMAMXMMMMAXAMAXMAMAMAXMXAAAAXMMMSMMASMMXMAMSMMMMSMSSMMMSAMXXSMSXXMAMXMMMSSSXXMAXAMMMMXAXAXAAMXMXMMAASAMAAXXMAXAXMXSXMXXXMASMMMAXXXMA
                SASASAMAMMAMAAAXSMMXSSXMAXASXSSMMMMMMXXAAAMXXMXAMXMXAAXXAAXXAAXSXXAASASASMMXSAXMAAMMSSXXASXXMMMMXSSMSAMXXSXSMASMSMMSXMSMSAAASMSMMMMMAMASMMMM
                XASAMXSXXXAMSXMMSXAXMAMSSSMSAMMAMXSMXSMMSXSASXSSSSMSSMSSMSMXSSXMMMMMMAMAMXAXMSSMMSMAXAASMMXMXMXMXXXMAXMXMMSMXXMAMMASAAAAMMSMMAAAASASXMSAMXAX
                MXMXMMXASXMMMSMAXMSMMSMMXAXMASXSMAAMASAAAAMAMAAMAXMAXXMMMMXMAMAAMXSXMXMMMMMXSAMAAXXMMMMMXAASASAMASAMXAXAXSAMSXMXMMASMMMSMAMXMSMSAMASMMAMXSMS
                SAAXMXSXMAXAMAMMXAAMAAAMMAMSXMAAMSSMASMMXMMAMMMMAMMAMXXAAMAMASXMMAMMMXMAXAXXMASMMSAMSSMAMSMSXSXSASMMXMSAXSAMXASXXMXSXXXAAASXXAAXAMSMMSSSMAMS
                SMSMXASAXXMAXMMXMSSSSSMMASXSXMMMMAAMASXXSASXSSXMXSMSSSSSSMXSMXXSMAMAMXSXSSSMXXMAMMAMAAXXMMAMXXXMXSAAAMMMMSXMSMMMAMSMMSMAMMSXMMSMMMXAMAAXMAAS
                XAAMMXSAMSASXXSAMMAMAAASXMAMSMMAMXXMAXAASMMMAXAMXSAAAXAAAXXMMSSXSSSMSASAAXXASMMSMSMMSSMSXSASMMSXAMMMMSAXAXMAXAASAMAXMAXAMMXMASMAXASMMMMMSMSX
                MSMSMXMXMXAMMMMMXSAMMMMSAMXMAMASXSAMXMMMSXMMASXMAMMMXMMMMMAAAXMASMAAMAMMAMMXMAAXXXAAXAXXAMAMAMSMSXAAAMAMXSXSSSMSXXXSXMSMSMAASMSMMXSXMXAMAMMA
                MAAAMAMSSMMMXXAMMXAMXXXSMMXSMSAXAMXAXXSAXAXMASMMASMSAXXAXSMMMXMXMSMXMAMXMMSSMMMMASMMSSMMSMMMXMXAMAMMMSAMMMMMAMXXMAXSMMAMAXMMMXAMMMMAMSMSAMXX
                SMSMMASAAAAAXXMSASMMMMMMAMXXMMASXXXXXMMMSSMMASAMXSAAXMMMXSXMMXSXMASAXASAAXAASAMMMMMXAMAAMAMXMXMXMAMAASAMAAXMAMXAMXXMASMSAMSASXSSXXMAMMXSAMSX
                XMAMMMSMSSMSSMAMASAAAXAAASXAXMAMASXMXSAXAAAXAMXMAMMMAAXMMSAMMMMAXXSMSMSXSMSSMXAAAAXMASMMXAMMXXMASASMXSASMSMMXMMXXMASXMAMXXSASAAXMMSSSMAMMMSA
                XMASXAXXMXXAAMAMXSMMMMXXMSXMMMMSAMXSASXSSSMMSXXMAXAXMXSAAMXMAASXMAXXAXMMXAMXXSSSSMSAMXAASXMAXSXMSASMMSMMAXAMAXMASAXMAMMMSASAMMMMAMAMXMAMAASM
                XMAMMSMASXMMXMAXXMXSSXSMMSAMAAXMXSAMASAMAMXAAMSMMMSAAAMMMMASXXAAMMMSMSXAXAMMXXMAXAXXAXMMAMXSXSAMXAXMAMAMASAMXSMAMSAMXMAMAAMAMXAASMASXMSSMMXM
                SMASAXMAMMMSMSSXSXAMMAAAAXAXSSXSAMASAMAMXMMMXXAAXAAMMMSAAXAMXMSMAAXAASMMSAMXSMMMMMMSMSXAMAXXAMMMSMMMMSXMMMXMXXMAMMXMASXMMXMAXSXSASASMMMAMXSM
                XSAMXSMXSAAAXAAASMMSSSMMSSSMAAAMASAMXSXMSXMAMSSXMMSAMXMMMSASXAAMMMSMMMAXAMMASAAXAXXAAMMXMSMMAMSMSAAXMXMXAMSSSMXSSMAMMSSXSMSSMXMAXMXSAMSAMAAS
                MMXMAXMASMMSMMMMMAMMAXXXAAMMMMXSAMASMSAMMAMMMAXASAAAAXMAMSAMASXSAMAXAXXMSXMXSXMXXXSMSMAAAMAMAMAAXSMSAASMMSAAAAAMAXSMMXMXSAAXMASXSMMMMMSAMAXA
                ASAMXSAMXMAMAXAASXMMMMMSMMMSXXAMXSAMXXAXSASMMASMMASXSAMXXMAXXMAXAXAXMSMXXASXMASMSMAAXXSXSSSMSSSSMXXAMSSMMMMSMMMSAAXASMMAMMMMSAXAAAXMSASMMSMM
                XMAXAXMASMASAXSXSAMAXAMAAXAXMMMSAMMSMSXMXASAMXMMSAMXMXXXXMMMSMXSSMSXMAAXSMMASASAAAMAMAMAAAXAXAAAAXSMMMMAAMXXMXXMMMSAMAMXXAAAAMASMMMXMASMAMAS
                SSSMSSSXXMAMXMMXMASXMXMSAMXSAAAMASAAAAMSMMMXMAMXSAXXMASXMSMAAMMAAAMMSASMSASXMASXMMSAMAMMMMMXMMMMMMXAAAXSMSAXMAXXXAXAMSXASMMSAXXXAAASAMXMAXMM
                MAAAXMMMSMMXSAXASMMXAMXMASAMXMMSSMXSXSASAMAASXSASXMXMAXXAAMSMSMSMMMAMAMAXAMMSXXAXXSASXSAMXXASAXXXXMMMSMMAMASMXSSMMSXMXXMASMXXMASXMMMMXSXSSSM
                MSMMMAAAAXSXAAXAMMAMXAAXMMAMXSMXAAMMMMXSAMSXSAMAMAAXMSMMSMXMAXXMAMAAMAMXMMMXMMMMMXSAMXXASMSMXXSMMMSAAXAMXMSMMMMXAXAASXSXAMXMSMMMXMAXMASAXMAS
                XXXASXMSSSXMMMMSMMSSMSASXSXMAXMSMMMSXMASXMMAXMMMSMSMMAAMMMXMMMMSMMSSSXSAMSSMXAAAMXMMMMSMMMAMMMAMAAMMSMXMAMMAXSSSMMMSMAXMXSAMAXAAAXXSAAMXMSAM
                XSAMXMMMMMAMXSAXASMAAXAAAAMMMXAAXAMXAMAMMXMXXMAXAAAMMSSMASXMAMMAMXAAAASMXAAXXSSSSMSAAAASMSXXAAASMXSAMXAMAMMMMMAAAASAMMMSMSASMXMSMSAMMSMMAMAS
                AAMAMXXSASXMAMXMMMMMMMXMAMAAAASMSSSSSMAMMAAXMSASXXMSXMAXAMXXAMSAMSMSMMSXMSSMXAAAAAMSMSMSXSASXMMXAAMXMSXXSXXAAMXMMMMMSAAAASAMMSMAMXXMAMAMSXXM
                MAMSXSASAMXMSSMMSAAAAMAXAXSASXMAAAAAAMAMMSSMAAAXXASXMSAMXXSXAMMAMSAMAMXMMXAXAMMSMMMXXAAXAMXMMASMMMMMMSSMXASMMSASMSMXSMSSMMXMAAMXSSMMASAMMSSX
                XSSXAAAMXMXMAXAAMMXSASMSSMXAXXMMMMMMSSMSMXMASMSMSMMAMAAXMASMMMSAMMMMSXMAMSMMMXMXMMXXSAMMSAMXSAMAMXASAMAMMAMXASAXAAAMXMAXAMXMSAMMMAAAAMAMXAMX
                XXAMAMAMMSAMMMMSSMAXAAXAMAXMMMXXXXSAMXAXMASXMAAMXAXAMMMMMAXAAAAXSXMAMAAMASAMXAMAMXSMMXMXXAMAMASMMMMMASXMMAMMAMAMSMSMAMAXXAXMASAAXSXMASXMMMMX
                XXMMMXAAAXXXXAAAAMAMSMMMMSXAAXMAMSMMSMSMSASAMSMSSSSSSXSAMXSSMSSMXAAASAMXASAMSMSASAAAAAXSSXMASXMMASXSXMAASMXAMMXMMAMXXSXASMSMAAXSMMXXMMAMMMMX
                MMXASXSMMSSSSSSSSMXXMAMSAXMSMSMSMSAMAXAXMXSAMMMXAAAAAMSAXAMAAXMASMMMMASMXXAMAAXAMMSMMXXAAXSAMAMSAMMXMXSMMMSSXMAAMAMXMAMMXAAMAMMMMXASXSAXMAMS
                AAMXSAXSAAAXMAMXAAXMSAMMXSXMAXAAASXMASMMMASAMXMMMMMMMMSMMSSMXXAMMXAAXAXMASXMMSMXMAMMASMMMMMAXAMMASAXAAXASAAMASXSSSSXMXMXMXMXSSMASMMSASAXSAMM
                SSSSMMMAMMSMSMSSMMSAMXMMASAMXMSMMMAXAMMSMASMMAMMSXMMSAXXAXAAMMMSMSXSMMMSAMXAAMAMXSXSAAAAASXSSXSMXAXXMASAMMSMMMAAAAMMMASMSASXAAMAMAMMMMMMXASX
                XMMAASMSASAASXMAAAMXMAXMAXAMXMXMAXAMMMAAMMMXXAXXMASAMAMMSSXMAAMAMXXMAMXMAXXMMXAMAMAMXSSMSAAXAMXMAMSMSMMXMAAASMSMMMSAMMSASASMSMMSXMSAAAAXSMSM
                MXSSMMAXSSMSMASMMMSASMSMMSSMXSASMSSXSASXXSASXSSSSMMXSASAMXXMXXMASXAMAMXSXMXSXXSASMMMAMMXMAXMMAAXAXAASMXMMMSSXAXXMAXXSXMAMXMAMXMXASXXMSMXAAMX
                AMXASMXMAXMXMAMXAXSAMXAAAAAMXXASAAAASMXMMMASAMXAASMASAMXSASMSXSASMSAASAMMMXMASMAXAASASASMSAAXSMXMXMXMASXXAMAMSMMMXSAMXSAMXMXMMSMXMAXXAMSMMMX
                MXSAMMAMMMSSMMMMXMXXMASMMSMMSMMMMMMMMXMSSMMMAMMXMMXAMMMMMMSAAAXASAMSMMMSAAAMSMMSMSMSAMASAMMXAAMAMXMXMMSMMSMSAAAXAAMAMMSASXMASAAAAXAMMAMMXMAX
                AMMSMSXSXAAMAAAMSSSMMAMXAMXAAAXMMAMAMMMAAAASAMMSMSMSXMAAAMMMMSMAMMMAXASMXSXSMAAXAAXXAMSMXMXMSASASAMASXXAAAXASMSMMSMMMASXMAMSMSSSXMMXSAMSMSSS
                MXAXMAXXMMMXMMMSAAASMASMXSMSXSMMMAMAXAMSXXMSXSAAAAAMMSMSMSAMSAMXMXXAMXMMMMMAXMMSMSSMMMXAXMXXXASXSXSASASMMSSXXMXAMXASMMSASXMAAXXMXMMASXMAMAAS
                XMXMXMSXSSSXSAXMMMMMMASXASXMAMAASMXSSSXXAMMMMXXMSMMSASXAASMMMXSXXSAMXAAAAAXSXMAMAAMAAXXMSMSMSMMMSAMASAMAAAAMMMMSXSMMAMSXMASMSMMSMSMASASMSMMM
                MMAMAMAAXAAAMAMXSXMASAMMXXXSASAMXAAXXMAMMMAAXAMXXMASAXMMMMSSXMXMASASXXSSSSXMASAMXMSAMSMMAAAMAAAXMXMAMXSXMSMAAXAMXMASMMSASMMXAAXAAAMMSMMAAAXM
                ASASASMMMMMMMMSAMASASAMAMSMMAMMMMMMSAMXMXSSSMXSAMXMMMMMSXAASAMXAMSMMAMXAMXASAMXSSXSAMXMSMSMSSSMSMAMASAMXMAMSSMMSAMXSAMSASXMSSSSMSMSAMXMMSMMM
                XSASMSAAMXAXXMMASAMASXMAAAAMAMAAXASAMXAMAMAAAASXSAXASMAAAMXSMAXSAMXMXXMAMSAMASXXMASAMSXAAAXXAAXMMASMMMSASAMAAMASASASAMMXMAMXMAAAAAMXSAMXXMAM
                MMXMXSMMSASXMASXMASMMXSASXSMXSXSSMSMXSSSXMSMMMSAMXSMXMAMSAMMASAMXAXXASMXMASMMMXAMXMAAXSMSMMMSMMXSMSXMXSXSMMMSMXSAMASMMSXSAMXMMMSMSMXSXSMASMS""";
        PUZZLE = Objects.requireNonNullElse(puzzle,words);
    }

    public void solvePartOne() {

        List<String> lines = Arrays.stream(PUZZLE.split("\n")).filter(x -> !x.equals("\n")).toList();
        int res = 0;
        for(int i = 0; i < lines.size(); i++) {
            for (int j = 0; j < lines.get(i).length(); j++) {
                if(lines.get(i).charAt(j) == 'X') {
                    List<int[]> queue = findMs(lines,i,j);
                    for(char c : new char[]{'A','S'}) {
                        if(queue.isEmpty())
                            break;
                        List<int[]> follow = new ArrayList<>();
                        for (int[] arr: queue) {
                            int[] tmp = hasChar(lines,arr[0],arr[1],arr[2],arr[3],c);
                            if(tmp != null) {
                                int newY = tmp[0];
                                int newX = tmp[1];
                                follow.add(new int[] {newY, newX,arr[2],arr[3]});
                            }
                        }
                        queue = follow;
                    }
                    res += queue.size();
                }

            }
        }
        System.out.println("Number of XMAS is: " + res);
    }

    public void solvePartTwo() {
        List<String> lines = Arrays.stream(PUZZLE.split("\n")).filter(x -> !x.equals("\n")).toList();
        int res = 0;
        for(int i = 1; i < lines.size() -1 ; i++) {
            for (int j = 1; j < lines.get(i).length() -1; j++) {
                if (lines.get(i).charAt(j) == 'A') {
                    if (isCross(lines,i,j)) {
                        res++;
                    }
                }
            }
        }
        System.out.println("Number of X-MAS is: " + res);
    }

    public boolean isCross(List<String> lines, int i, int j) {
        char upLeft = lines.get(i-1).charAt(j-1);
        char upRight = lines.get(i-1).charAt(j+1);
        char downLeft = lines.get(i+1).charAt(j-1);
        char downRight = lines.get(i+1).charAt(j+1);
        boolean upLeftToDownRight = (upLeft == 'M' && downRight == 'S') || (upLeft == 'S' && downRight == 'M');
        boolean downLeftToUpRight = (downLeft == 'M' && upRight == 'S') || (downLeft == 'S' && upRight == 'M');
        return upLeftToDownRight && downLeftToUpRight;
    }

    public int[] hasChar(List<String> lines, int i, int j, int diffX, int diffY, char toFind) {
        if( (0 <= i + diffY && i+diffY < lines.size()) && (0 <= j + diffX && j + diffX < lines.get(i).length() ) ){
            if (lines.get(i + diffY).charAt(j + diffX) == toFind) {
                return new int[]{i + diffY,j + diffX};
            }
            return null;
        }
        return null;
    }

    public List<int []> findMs(List<String> lines, int i, int j) {
        List<int []> res = new ArrayList<>();
        for (int y = Math.max(i-1,0); y < Math.min(i+2,lines.size());y++) {
            for(int x = Math.max(j-1,0); x < Math.min(j+2,lines.get(i).length());x++ ) {
                if (lines.get(y).charAt(x) == 'M') {
                    int diffX = x -j;
                    int diffY = y -i;
                    res.add(new int[] {i+diffY,j+diffX,diffX,diffY});
                }
            }
        }
        return res;
    }
}
